# Étape 1 : Utilisation d'une image de base node
FROM node:20.17 AS development

ARG VITE_API_URL
ENV VITE_API_URL=http://localhost:3000/api

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste du code source
COPY . .

# Étape 6 : Exposer le port que Vite utilise (par défaut, c'est le 5173)
EXPOSE 5173

# Étape 7 : Démarrer l'application en mode développement avec vite
CMD ["npm", "run", "dev"]
